version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "server/package-lock.json" }}
      - run:
          name: install-npm-wee
          command: cd server && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "server/package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: cd server && npm test
